
export const MECHANICAL_FACTS = [
  "Thread pitch is the distance between two corresponding points on adjacent threads measured parallel to the axis.",
  "The modulus of elasticity is the measure of stiffness of a material.",
  "A worm gear is used to transmit power between non-intersecting shafts at right angles.",
  "Pascal's Law states that pressure exerted anywhere in a confined incompressible fluid is transmitted equally in all directions.",
  "The Carnot cycle is a theoretical ideal thermodynamic cycle that provides the maximum possible efficiency.",
  "Entropy is a measure of the molecular disorder or randomness of a system.",
  "The yield point is the stress level at which a metal or other material ceases to behave elastically.",
  "Cavitation in pumps occurs when the pressure of the liquid falls below its vapor pressure.",
  "A flywheel is a mechanical device specifically designed to efficiently store rotational energy.",
  "The Rankine cycle is the fundamental operating cycle of all thermal power plants where an operating fluid is continuously evaporated and condensed.",
  "Poisson's ratio is the ratio of transverse strain to axial strain.",
  "Fatigue is the weakening of a material caused by repeatedly applied loads.",
  "A universal joint is a joint or coupling connecting rigid rods whose axes are inclined to each other.",
  "The Reynolds number is used to predict flow patterns in different fluid flow situations.",
  "The Zeroth Law of Thermodynamics defines temperature and equilibrium.",
  "An adiabatic process is one in which no heat is gained or lost by the system.",
  "The mechanical advantage of a lever is the ratio of the output force to the input force.",
  "Kinematic viscosity is the ratio of dynamic viscosity to density.",
  "The Geneva drive provides intermittent rotary motion from continuous rotation.",
  "Babbitt metal is a tin or lead-based alloy used for the bearing surface in a plain bearing.",
  "Annealing is a heat treatment process that alters the physical and sometimes chemical properties of a material.",
  "Torsion is the twisting of an object due to an applied torque.",
  "A spur gear has teeth that are straight and parallel to the axis of the shaft.",
  "A rack and pinion converts rotational motion into linear motion.",
  "The first law of thermodynamics is a version of the law of conservation of energy.",
  "Young's modulus is a numerical constant that describes the elastic properties of a solid undergoing tension or compression.",
  "A toggle joint is a mechanism consisting of two levers joined together which can provide very high forces.",
  "Hydrostatic pressure is the pressure exerted by a fluid at equilibrium at a given point within the fluid.",
  "Surface tension is the tendency of liquid surfaces to shrink into the minimum surface area possible.",
  "The coefficient of friction is a dimensionless scalar value which describes the ratio of the force of friction between two bodies.",
  "A governor is a device used to measure and regulate the speed of a machine.",
  "Centrifugal force is an inertial force that appears to act on all objects when viewed in a rotating frame of reference.",
  "A planetary gearset consists of one or more outer gears, or planet gears, revolving about a central, or sun gear.",
  "Vickers hardness test is a method to measure the hardness of materials.",
  "The triple point of a substance is the temperature and pressure at which the three phases coexist in thermodynamic equilibrium.",
  "Specific heat capacity is the amount of heat energy required to raise the temperature of a substance per unit of mass.",
  "A camshaft is a shaft to which a cam is fastened or of which a cam forms an integral part.",
  "The Otto cycle is an idealized thermodynamic cycle that describes the functioning of a typical spark ignition piston engine.",
  "Bernoulli's principle states that an increase in the speed of a fluid occurs simultaneously with a decrease in static pressure.",
  "Buckling is a mathematical instability that leads to a failure mode.",
  "Tolerance is the total amount a specific dimension is permitted to vary.",
  "The Mohs scale of mineral hardness is a qualitative ordinal scale characterizing scratch resistance.",
  "A scotch yoke is a reciprocating motion mechanism, converting the linear motion of a slide into rotational motion.",
  "Nitinol is a metal alloy of nickel and titanium with shape memory properties.",
  "Creep is the tendency of a solid material to move slowly or deform permanently under the influence of persistent mechanical stresses.",
  "The Mach number is the ratio of the speed of an object to the speed of sound.",
  "A differential gear allows the outer drive wheel to rotate faster than the inner drive wheel during a turn.",
  "Isentropic process is a thermodynamic process in which the entropy of the system remains constant.",
  "The Nusselt number is the ratio of convective to conductive heat transfer across a boundary.",
  "Hardening is a metallurgical metalworking process used to increase the hardness of a metal.",
  "Laminar flow is characterized by fluid particles following smooth paths in layers.",
  "Turbulent flow is a flow regime characterized by chaotic changes in pressure and flow velocity.",
  "Heat flux is the flow of energy per unit of area per unit of time.",
  "Internal energy is the total energy contained by a thermodynamic system.",
  "A four-bar linkage is the simplest movable closed-chain linkage.",
  "Milling is the process of machining using rotary cutters to remove material by advancing a cutter into a workpiece.",
  "Forging is a manufacturing process involving the shaping of metal using localized compressive forces.",
  "Extrusion is a process used to create objects of a fixed cross-sectional profile.",
  "The Brinell scale characterizes the indentation hardness of materials.",
  "A pressure vessel is a container designed to hold gases or liquids at a pressure substantially different from the ambient pressure.",
  "Fatigue limit is the stress level below which an infinite number of loading cycles can be applied to a material without causing fatigue failure.",
  "Damping is an influence within or upon an oscillatory system that has the effect of reducing or preventing its oscillation.",
  "A spline is a series of parallel grooves or keys on a shaft that mesh with corresponding grooves in a mating part.",
  "The venturi effect is the reduction in fluid pressure that results when a fluid flows through a constricted section of a pipe.",
  "A heat sink is a passive heat exchanger that transfers the heat generated by an electronic or a mechanical device to a fluid medium.",
  "Torque is the rotational equivalent of linear force.",
  "Stiffness is the extent to which an object resists deformation in response to an applied force.",
  "Strength of materials is a subject which deals with loads, deformations and the stability of structures.",
  "Elasticity is the ability of a body to resist a distorting influence and to return to its original size and shape when that influence or force is removed.",
  "Plasticity describes the deformation of a (solid) material undergoing non-reversible changes of shape in response to applied forces.",
  "A bearing is a machine element that constrains relative motion to only the desired motion and reduces friction between moving parts.",
  "A bushing is an independent plain bearing that is inserted into a housing to provide a bearing surface for rotary applications.",
  "A keyway is a slot in a hub or shaft that accommodates a key to prevent relative rotation between the two parts.",
  "Interference fit is a fastening between two parts which is achieved by friction after the parts are pushed together.",
  "A cotter pin is a metal fastener with two tines that are bent during installation.",
  "The Prandtl number is a dimensionless number that approximates the ratio of momentum diffusivity to thermal diffusivity.",
  "A solenoid is a type of electromagnet, the purpose of which is to generate a controlled magnetic field through a tight loop of wire.",
  "Conduction is the transfer of internal energy by microscopic collisions of particles and movement of electrons within a body.",
  "Convection is the transfer of heat from one place to another by the movement of fluids.",
  "Radiation is the emission or transmission of energy in the form of waves or particles through space or through a material medium.",
  "A check valve is a valve that normally allows fluid to flow through it in only one direction.",
  "A manifold is a wide and/or bigger pipe or channel into which smaller pipes or channels lead.",
  "Pneumatics is a branch of engineering that makes use of gas or pressurized air.",
  "Hydraulics is a technology and applied science using engineering, chemistry, and other sciences involving the mechanical properties and use of liquids.",
  "A crankshaft is a mechanical part able to perform a conversion between reciprocating motion and rotational motion.",
  "A piston is a component of reciprocating engines, reciprocating pumps, gas compressors and pneumatic cylinders.",
  "The compression ratio of an internal combustion engine is a value that represents the ratio of the volume of its combustion chamber from its largest capacity to its smallest capacity.",
  "The displacement of an engine is the volume swept by all the pistons inside the cylinders.",
  "Horsepower is a unit of measurement of power, or the rate at which work is done.",
  "A turbocharger is a turbine-driven forced induction device that increases an internal combustion engine's efficiency and power output.",
  "An intercooler is an intake air cooling device used commonly on turbocharged and supercharged engines.",
  "The drivetrain of a motor vehicle is the group of components that deliver power to the driving wheels.",
  "A clutch is a mechanical device that engages and disengages power transmission, especially from a drive shaft to a driven shaft.",
  "A transmission is a machine in a power transmission system, which provides controlled application of the power.",
  "The torque converter is a type of fluid coupling which transfers rotating power from a prime mover.",
  "Suspension is the system of tires, tire air, springs, shock absorbers and linkages that connects a vehicle to its wheels.",
  "A shock absorber is a mechanical or hydraulic device designed to absorb and damp shock impulses.",
  "A leaf spring is a simple form of spring commonly used for the suspension in wheeled vehicles.",
  "A coil spring is a mechanical device which is typically used to store energy and subsequently release it.",
  "The Ackermann steering geometry is a geometric arrangement of linkages in the steering of a car or other vehicle designed to solve the problem of wheels on the inside and outside of a turn needing to trace out circles of different radii."
];
